version: '3'
services:
    app:
        container_name: application
        build:
            context: .
            dockerfile: Dockerfile.dev
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:5173'
        networks:
            - web_network
        environment:
            TZ: 'Asia/Kuala_Lumpur'
            CHOKIDAR_USEPOLLING: 'true'
        volumes:
          - .:/app
          - /app/node_modules
networks:
    web_network:
        driver: bridge
